import type { Metadata } from "next";
import localFont from '@next/font/local';
import "./globals.css";

const calibri = localFont({
  src: '../public/calibri.ttf',
  variable: '--font-calibri'
})

const catchye = localFont({
  src: '../public/catchye.otf',
  variable: '--font-catchye'
})

const helveticaMedium = localFont({
  src: '../public/helvetica-m.ttf',
  variable: '--font-helveticam'
})

const helveticaRegular = localFont({
  src: '../public/helvetica-r.ttf',
  variable: '--font-helveticar'
})

const helveticaRounded = localFont({
  src: '../public/helvetica-rounded.otf',
  variable: '--font-helveticarounded'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={catchye.variable + " " + calibri.variable + " " + helveticaMedium.variable + " " + helveticaRegular.variable + " " + helveticaRounded.variable}>{children}
      
      </body>
    </html>
  );
}
